using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text.Json;
using vue_spotify_app.Classes;
using vue_spotify_app.Classes.APIData;
using vue_spotify_app.Server.Data;

namespace vue_spotify_app.Server
{
    /// <summary>
    /// Service for handling the generation, retrieval and refreshing of Spotify access tokens using the PKCE flow.
    /// </summary>
    public class AuthService
    {
        private readonly SpotifyOptions _spotifyOptions;
        private readonly DataContext _dataContext;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly HttpClient _httpClient;

        public AuthService(IOptions<SpotifyOptions> options, DataContext dataContext, IHttpContextAccessor contextAccessor, HttpClient httpClient)
        {
            _spotifyOptions = options.Value;
            _dataContext = dataContext;
            _httpContextAccessor = contextAccessor;
            _httpClient = httpClient;
        }

        /// <summary>
        /// Creates a random code verifier string for PKCE flow.
        /// </summary>
        /// <returns>A URL-safe Base64 encoded string.</returns>
        public static string GenerateCodeVerifier()
        {
            // Creates a variable with 64 bytes of random data, then encodes it in URL-safe Base64 format.
            var randomBytes = new byte[64];
            using var rng = System.Security.Cryptography.RandomNumberGenerator.Create();
            rng.GetBytes(randomBytes);
            return Convert.ToBase64String(randomBytes).TrimEnd('=').Replace('+', '-').Replace('/', '_');
        }

        /// <summary>
        /// Creates a code challenge from the code verifier using SHA256 and Base64 URL encoding.
        /// </summary>
        /// <param name="codeVerifier">A code verifier string generated by GenerateCodeVerifier.</param>
        /// <returns>A URL-safe Base64 encoded string representing the code challenge.</returns>
        public static string GenerateCodeChallenge(string codeVerifier)
        {
            // Takes the code verifier, gets the SHA256 hash, and encodes the result in URL-safe Base64 format.
            using var sha256 = System.Security.Cryptography.SHA256.Create();
            var hash = sha256.ComputeHash(System.Text.Encoding.UTF8.GetBytes(codeVerifier));
            return Convert.ToBase64String(hash).TrimEnd('=').Replace('+', '-').Replace('/', '_');
        }

        /// <summary>
        /// Generates a cryptographically secure, URL-safe random state string.
        /// </summary>
        /// <returns>A base64-encoded, URL-safe random string.</returns>
        public static string GenerateState()
        {
            // Creates a variable with 16 bytes of random data, then encodes it in URL-safe Base64 format.
            var randomBytes = new byte[16];
            using var rng = System.Security.Cryptography.RandomNumberGenerator.Create();
            rng.GetBytes(randomBytes);
            return Convert.ToBase64String(randomBytes).TrimEnd('=').Replace('+', '-').Replace('/', '_');
        }

        /// <summary>
        /// Generates a Spotify authorisation URL for PKCE flow.
        /// </summary>
        /// <param name="state"></param>
        /// <param name="codeVerifier">The code verifier string generated for the authorisation request, which is stored in the current session for the token exchange.</param>
        /// <returns>A redirect URL that is used to authorise via Spotify.</returns>
        public string GenerateRedirectURL(out string state, out string codeVerifier)
        {
            // Generates a code verifier, code challenge and state string.
            codeVerifier = GenerateCodeVerifier();
            var codeChallenge = GenerateCodeChallenge(codeVerifier);
            state = GenerateState();

            // Stores the code verifier in the current session for later use.
            _httpContextAccessor.HttpContext!.Session.SetString("code_verifier", codeVerifier);

            // Gets the scopes from the Spotify options to use in the query parameters.
            string scopes = string.Join(" ", _spotifyOptions.Scopes);

            // Generates the query parameters for the authorisation URL.
            var queryParams = new Dictionary<string, string>
            {
                { "client_id", _spotifyOptions.ClientID },
                { "response_type", "code" },
                { "redirect_uri", _spotifyOptions.RedirectURL },
                { "scope", scopes },
                {"state", state},
                {"code_challenge_method", "S256"},
                {"code_challenge", codeChallenge}
            };
            return QueryHelpers.AddQueryString("https://accounts.spotify.com/authorize", queryParams);
        }

        /// <summary>
        /// Gets a Spotify access token using the authorisation code provided.
        /// </summary>
        /// <param name="code">The authorisation code used to exchange for an access token.
        /// <param name="state"></param>
        /// <returns></returns>
        /// <exception cref="Exception"></exception>
        public async Task<SpotifyToken?> GetToken(string code, string state, bool returnToken = true)
        {
            var codeVerifier = _httpContextAccessor.HttpContext!.Session.GetString("code_verifier");
            if (codeVerifier == null)
                throw new Exception("Code verifier not found in session.");

            var data = new Dictionary<string, string>
            {
                { "client_id", _spotifyOptions.ClientID },
                { "grant_type", "authorization_code" },
                { "code", code },
                { "redirect_uri", _spotifyOptions.RedirectURL },
                { "code_verifier", codeVerifier }
            };

            var response = await _httpClient.PostAsync("https://accounts.spotify.com/api/token", new FormUrlEncodedContent(data));
            //response.EnsureSuccessStatusCode();
            var content = await response.Content.ReadAsStringAsync();
            if(!response.IsSuccessStatusCode)
                throw new Exception($"Error fetching token: {content}");
            var rawToken = JsonSerializer.Deserialize<AccessToken>(content)!;
            var token = new SpotifyToken
            {
                AccessToken = rawToken.access_token,
                RefreshToken = rawToken.refresh_token,
                ExpirationUTC = DateTime.UtcNow.AddSeconds(rawToken.expires_in)
            };
            if (returnToken)
            {
                return token;
            }
            else
            {
                var request = new HttpRequestMessage(HttpMethod.Get, "https://api.spotify.com/v1/me");

                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token.AccessToken);

                response = await _httpClient.SendAsync(request);

                content = await response.Content.ReadAsStringAsync();
                if (!response.IsSuccessStatusCode)
                    throw new Exception($"Error fetching user data: {content}");

                content = await response.Content.ReadAsStringAsync();
                var spotifyUser = JsonSerializer.Deserialize<UserProfile>(content);

                var user = await _dataContext.Users.Include(u => u.SpotifyToken).FirstOrDefaultAsync(u => u.SpotifyUserID == spotifyUser.id);
                if (user == null)
                {
                    user = new User
                    {
                        SpotifyUserID = spotifyUser.id,
                        DisplayName = spotifyUser.display_name,
                        SpotifyToken = token
                    };
                    _dataContext.Users.Add(user);
                }
                else
                {
                    user.DisplayName = spotifyUser.display_name;
                    user.SpotifyToken = token;
                    _dataContext.Users.Update(user);
                }

                await _dataContext.SaveChangesAsync();

                var claims = new List<Claim>{
                    new Claim(ClaimTypes.NameIdentifier, user.ID.ToString()),
                    new Claim("spotify_id", user.SpotifyUserID)
                };

                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await _httpContextAccessor.HttpContext!.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity));

                return null;
            }
        }

        public async Task Logout()
        {
            await _httpContextAccessor.HttpContext!.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        }

        public async Task RefreshToken(SpotifyToken token)
        {
            var data = new Dictionary<string, string>
            {
                { "client_id", _spotifyOptions.ClientID },
                { "grant_type", "refresh_token" },
                { "refresh_token", token.RefreshToken }
            };
            using var httpClient = new HttpClient();
            var response = await httpClient.PostAsync("https://accounts.spotify.com/api/token", new FormUrlEncodedContent(data));
            var content = await response.Content.ReadAsStringAsync();
            if(!response.IsSuccessStatusCode)
                throw new Exception($"Error refreshing token: {content}");
            var rawToken = JsonSerializer.Deserialize<AccessToken>(content)!;
            token.AccessToken = rawToken.access_token;
            token.ExpirationUTC = DateTime.UtcNow.AddSeconds(rawToken.expires_in);

            if (!string.IsNullOrEmpty(rawToken.refresh_token))
                token.RefreshToken = rawToken.refresh_token;
            _dataContext.SpotifyTokens.Update(token);
            await _dataContext.SaveChangesAsync();
        }

        public async Task<string> GetValidToken(Guid userId)
        {
            var token = await _dataContext.SpotifyTokens.FindAsync(userId);
            if (token == null)
                throw new Exception("No token found for user.");
            if (token.ExpirationUTC <= DateTime.UtcNow)
            {
                await RefreshToken(token);
            }
            return token.AccessToken;
        }        
    }
}
